on: push

jobs:

  info:

    runs-on: ubuntu-latest
    env:
      THIS_RELEASE: 0.3.0
    steps:
      - uses: actions/checkout@v2
        
      - name: get latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RELEASE=$(hub release | grep -E '^[0-9]+.[0-9]+.[0-9]+$' | sort -r | head -n 1)
          echo "latest release: $LATEST_RELEASE"
          echo ::set-env name=LATEST_RELEASE::$LATEST_RELEASE
          
      - env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: |
          echo "ENV_CONTEXT: $ENV_CONTEXT"

      - if: env.THIS_RELEASE == env.LATEST_RELEASE
        run: |
          MAJOR_VERSION=$(echo $THIS_RELEASE | grep -Eo '^[0-9]+')
          MAJOR_TAG="v$MAJOR_VERSION"
          echo "this release is the latest, updating major tag $MAJOR_TAG"
      
      - if: env.THIS_RELEASE != env.LATEST_RELEASE
        run: echo "this release is not the latest (perhaps a patch?), not updating major tag"
        
