on: push

jobs:

  info:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: hub version
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: hub release
