on: push

jobs:

  info:
  
    runs-on: ubuntu-latest
    steps:
      - run: hub version
      - name: run hub commands
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
             hub release
