on: push

jobs:

  info:

    runs-on: ubuntu-latest
    env:
      THIS_RELEASE: 0.2.0
    steps:
      - uses: actions/checkout@v2
        
      - name: get latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST_RELEASE=$(hub release | grep -E '^[0-9]+.[0-9]+.[0-9]+$' | sort -r | head -n 1)
          echo "latest release: $LATEST_RELEASE"
          echo ::set-env name=LATEST_RELEASE::$LATEST_RELEASE
          
      - env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: |
          echo "ENV_CONTEXT: $ENV_CONTEXT"

        
