on:
  release:
    types: [published]
    
jobs:

  info:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          THIS_RELEASE: ${{ toJson(github.event.release.name) }}
        run: |
          echo "this release: $THIS_RELEASE"
          LATEST_RELEASE=$(hub release | grep -E '^[0-9]+.[0-9]+.[0-9]+$' | sort -r | head -n 1)
          echo "latest release: $LATEST_RELEASE"
  
